server:
  port: 8081
spring:
  application:
    name: bootcamp-productservice
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
bootcamp:
  price-service:
      url.port: http://localhost:9090/bootcamp-priceservice/get-price{id}